-- Add referrer1 and referrer2 fields to Deal table
ALTER TABLE "Deal"
  ADD COLUMN IF NOT EXISTS "referrer1UserId"     INTEGER,
  ADD COLUMN IF NOT EXISTS "referrer1RakebackPct" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "referrer1RebatePct"   DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "referrer2UserId"     INTEGER,
  ADD COLUMN IF NOT EXISTS "referrer2RakebackPct" DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "referrer2RebatePct"   DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE "Deal"
  ADD CONSTRAINT IF NOT EXISTS "Deal_referrer1UserId_fkey"
    FOREIGN KEY ("referrer1UserId") REFERENCES "User"(id) ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE "Deal"
  ADD CONSTRAINT IF NOT EXISTS "Deal_referrer2UserId_fkey"
    FOREIGN KEY ("referrer2UserId") REFERENCES "User"(id) ON DELETE SET NULL ON UPDATE CASCADE;
